/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Connexion.Connexion;
import DAO.PersonneDAO;
import Extension.CrypteMdp;
import Extension.IconesPerso;
import Extension.LienHypertexte;
import Metier.Personne;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author utilisateur
 */
public class Accueil extends javax.swing.JFrame
{
	//------------------------- ATTRIBUTS -------------------------//
	private final String iconeAdresse = "../icones/iconeQuitter.png";
	//------------------------- ATTRIBUTS -------------------------//
	
	public Accueil() {
//		Connexion service = new Connexion();
//		service.verifService();
		initComponents();
		setTitle("MyPass - Gestionnaire de mot de passe");
		
		//------------------------- MISE EN FORME -------------------------//
		
			//------------------------- DEFINITION / ASSOCIATION ICONE -------------------------//
		IconesPerso boutonQuitter = new IconesPerso();
		boutonQuitter.iconeBouton(quitter, iconeAdresse);
			//------------------------- DEFINITION / ASSOCIATION ICONE -------------------------//
			
			//------------------------- LIEN HYPERTEXTE -------------------------//
		LienHypertexte lienlabel = new LienHypertexte();
		inscription.setEnabled(true);
		lienlabel.souligner(true, inscription);
		lienlabel.souligner(true, oubliMdp);
			//------------------------- LIEN HYPERTEXTE -------------------------//
			
		//------------------------- POSITIONNEMENT FENETRE -------------------------//
			// GESTION AUTO DU POSITIONNEMENT EN CENTRE VERTICAL / HORIZONTAL
		this.setLocationRelativeTo(this);
		//------------------------- POSITIONNEMENT FENETRE -------------------------//
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        titre = new javax.swing.JLabel();
        lien = new javax.swing.JLabel();
        labelPseudo = new javax.swing.JLabel();
        saisiePseudo = new javax.swing.JTextField();
        labelMdp = new javax.swing.JLabel();
        connexion = new javax.swing.JButton();
        labelQuestion = new javax.swing.JLabel();
        inscription = new javax.swing.JLabel();
        sousTitre = new javax.swing.JLabel();
        saisieMdp = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        quitter = new javax.swing.JButton();
        oubliMdp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        titre.setFont(new java.awt.Font("Source Sans Pro", 1, 36)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("MyPass");

        lien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lien.setText("Programmé par STRYJEWSKI Nicolas");
        lien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienMouseExited(evt);
            }
        });

        labelPseudo.setText("Pseudo :");

        labelMdp.setText("Mot de passe :");

        connexion.setText("Se connecter");
        connexion.setMaximumSize(new java.awt.Dimension(150, 50));
        connexion.setMinimumSize(new java.awt.Dimension(150, 50));
        connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionActionPerformed(evt);
            }
        });

        labelQuestion.setText("Pas encore inscrit ?");

        inscription.setText("S'inscrire");
        inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscriptionMouseClicked(evt);
            }
        });

        sousTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sousTitre.setText("Votre gestionnaire de mot de passe");

        saisieMdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saisieMdpKeyPressed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSeparator1, org.jdesktop.beansbinding.ELProperty.create("${orientation}1"), jSeparator1, org.jdesktop.beansbinding.BeanProperty.create("orientation"));
        bindingGroup.addBinding(binding);

        quitter.setText("Quitter");
        quitter.setMaximumSize(new java.awt.Dimension(150, 50));
        quitter.setMinimumSize(new java.awt.Dimension(150, 50));
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });

        oubliMdp.setText("Mot de passe oublié ?");
        oubliMdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oubliMdpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sousTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuestion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMdp)
                            .addComponent(saisieMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saisiePseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPseudo)
                            .addComponent(connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oubliMdp))
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(inscription)
                        .addGap(27, 27, 27)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saisieMdp, saisiePseudo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sousTitre)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelQuestion)
                        .addGap(3, 3, 3)
                        .addComponent(inscription))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPseudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saisiePseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMdp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saisieMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oubliMdp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(quitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lien))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
//------------------------- GESTION EVENEMENTS -------------------------//
    private void lienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienMouseEntered
		//Fonction pour survol de souris
		LienHypertexte lienlabel = new LienHypertexte();
		lien.setEnabled(true);
		lienlabel.souligner(true, lien);
    }//GEN-LAST:event_lienMouseEntered

    private void lienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienMouseExited
		//Fonction lors de l'arret du survol
		LienHypertexte lienlabel = new LienHypertexte();
		lienlabel.souligner(false, lien);
    }//GEN-LAST:event_lienMouseExited

    private void lienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienMouseClicked
		//Ouverture du navigateur par defaut du systeme + ouverture page definie
		String adresse = "https://www.linkedin.com/in/stryjewskinicolas/";
		LienHypertexte lienlabel = new LienHypertexte();
		lienlabel.ouvertureLien(adresse);
    }//GEN-LAST:event_lienMouseClicked

    private void inscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseClicked
        CreerUtilisateur inscription = new CreerUtilisateur();
		inscription.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_inscriptionMouseClicked

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitterActionPerformed

    private void connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionActionPerformed
        String pseudo = saisiePseudo.getText();
		char[] c = saisieMdp.getPassword();
        String mdp = new String(c);
		
		//------------------------- CRYPTAGE DU MOT DE PASSE -------------------------//
			CrypteMdp mdpCrypte = new CrypteMdp(mdp);
			String valeurMdpCrypte = mdpCrypte.chiffrer();
		//------------------------- CRYPTAGE DU MOT DE PASSE -------------------------//
		
		PersonneDAO personneDao = new PersonneDAO();
		Personne personne;
		personne = personneDao.chargePersonne(pseudo, valeurMdpCrypte);
		
		if(personne.getId() == 0)
		{
			JOptionPane.showMessageDialog(null, "Les informations du compte ne sont pas reconnues./n", "Connexion impossible", JOptionPane.ERROR_MESSAGE);
			saisiePseudo.setText("");
			saisieMdp.setText("");
		}
		else
		{
			ListeCompte connexion = new ListeCompte(personne.getId());
			connexion.setVisible(true);
			this.dispose();
		}
    }//GEN-LAST:event_connexionActionPerformed

    private void saisieMdpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saisieMdpKeyPressed
        int key = evt.getKeyCode();
		if(key == KeyEvent.VK_ENTER)
		{
			String pseudo = saisiePseudo.getText();
			char[] c = saisieMdp.getPassword();
			String mdp = new String(c);
			
			//------------------------- CRYPTAGE DU MOT DE PASSE -------------------------//
			CrypteMdp mdpCrypte = new CrypteMdp(mdp);
			String valeurMdpCrypte = mdpCrypte.chiffrer();
			//------------------------- CRYPTAGE DU MOT DE PASSE -------------------------//

			PersonneDAO personneDao = new PersonneDAO();
			Personne personne;;
			personne = personneDao.chargePersonne(pseudo, valeurMdpCrypte);

			if(personne.getId() == 0)
			{
				JOptionPane.showMessageDialog(null, "Les informations du compte ne sont pas reconnues.", "Connexion impossible", JOptionPane.ERROR_MESSAGE);
				saisiePseudo.setText("");
				saisieMdp.setText("");
			}
			else
			{
				ListeCompte connexion = new ListeCompte(personne.getId());
				connexion.setVisible(true);
				this.dispose();
			}
		}
    }//GEN-LAST:event_saisieMdpKeyPressed

    private void oubliMdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oubliMdpMouseClicked
        RecupMdp recupMdp = new RecupMdp();
		recupMdp.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_oubliMdpMouseClicked
	//------------------------- GESTION EVENEMENTS -------------------------//
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
				UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Accueil().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connexion;
    private javax.swing.JLabel inscription;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMdp;
    private javax.swing.JLabel labelPseudo;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel lien;
    private javax.swing.JLabel oubliMdp;
    private javax.swing.JButton quitter;
    private javax.swing.JPasswordField saisieMdp;
    private javax.swing.JTextField saisiePseudo;
    private javax.swing.JLabel sousTitre;
    private javax.swing.JLabel titre;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
